export const TOKENS = {
    AppConfig:               Symbol('AppConfig'),
    MongoHelper:             Symbol('MongoHelper'),
    ProjectDbService:        Symbol('ProjectDbService'),
    TaskDbService:           Symbol('TaskDbService'),
    NoteDbService:           Symbol('NoteDbService'),
    CascadeDeleteService:    Symbol('CascadeDeleteService'),
    ReparentService:         Symbol('ReparentService'),
    LlmModelDbService:       Symbol('LlmModelDbService'),
    GroupDbService:          Symbol('GroupDbService'),
    ProjectionOrderService:  Symbol('ProjectionOrderService'),
    DataDefinitionDbService: Symbol('DataDefinitionDbService'),
    DashboardDbService:      Symbol('DashboardDbService'),
    AppStateDbService:       Symbol('AppStateDbService'),
};
